Feature/patch users route
marcelosj3/capstone-q4 pull request #38
Opened 2022-06-17 12:19 UTC by pronguto

2022-06-17 16:53 UTC, marcelosj3 requested changes

2022-06-17 16:53 UTC, marcelosj3 commented on src/__tests__/services/users/patch/patch.users.service.spec.ts
> +describe('Patch an user', () => {
Acho que seria uma boa criar cenários pra quando der algum erro também

2022-06-17 16:55 UTC, marcelosj3 requested changes

2022-06-17 16:55 UTC, marcelosj3 commented on src/services/user.service.ts
> +import userRepository from '../repositories/user.repository';
Padronizar utilizar o `UserRepository` pra não ter mais de uma importação

2022-06-17 18:04 UTC, LeandroMedvedev submitted a review, later dismissed

2022-06-19 17:47 UTC, pronguto commented on src/__tests__/services/users/patch/patch.users.service.spec.ts
> +describe('Patch an user', () => {
feito

2022-06-19 17:47 UTC, pronguto commented on src/services/user.service.ts
> +import userRepository from '../repositories/user.repository';
Feito

2022-06-19 20:32 UTC, marcelosj3 requested changes

2022-06-19 20:32 UTC, marcelosj3 commented on src/__tests__/services/users/patch/__scenarios__.ts
> +// export const patchUserEmailWithoutOldPassword = {
remove os comentários

2022-06-19 20:32 UTC, marcelosj3 commented on src/__tests__/services/users/patch/patch.users.service.spec.ts
> +  // test('Should pactch an user email and password sucessfully', async () => {
remover os comentários aqui também

2022-06-19 20:32 UTC, marcelosj3 commented on src/routes/user.routes.ts
> +  router.delete(
trocar por patch

2022-06-19 23:35 UTC, LeandroMedvedev submitted a review, later dismissed

2022-06-20 02:31 UTC, pronguto commented on src/__tests__/services/users/patch/__scenarios__.ts
> +// export const patchUserEmailWithoutOldPassword = {
Feito, tinha esquecido.

2022-06-20 02:31 UTC, pronguto commented on src/__tests__/services/users/patch/patch.users.service.spec.ts
> +  // test('Should pactch an user email and password sucessfully', async () => {
Feito.

2022-06-20 02:31 UTC, pronguto commented on src/routes/user.routes.ts
> +  router.delete(
Feito

2022-06-20 03:08 UTC, marcelosj3 approved these changes

2022-06-20 10:38 UTC, JOSUE-ASV approved these changes

2022-06-20 12:07 UTC, merged