feat: user schema
marcelosj3/capstone-q4 pull request #8
Opened 2022-06-13 21:26 UTC by LeandroMedvedev

2022-06-13 23:55 UTC, pronguto approved these changes

2022-06-14 01:50 UTC, marcelosj3 requested changes

2022-06-14 01:50 UTC, marcelosj3 commented on src/schemas/user/updateUser.schema.ts
> +      .default(CompanyRole.CLIENT)
Não da errado deixar esse valor default aqui? Digamos que eu seja um employee e tente me atualizar sem passar a chave de companyRole, ele pegaria esse valor default pra preencher a chave faltante? A gente consegue validar isso?

2022-06-14 01:50 UTC, marcelosj3 commented on src/schemas/user/serializedUser.schema.ts
> +  isActive: boolean().default(false).optional(),
A gente precisa de algum valor default nesse schema? como é uma serialização eu imagino que os valores já tem que existir e a gente só precisa re-confirmar os tipos dele, ou não?

2022-06-14 01:50 UTC, marcelosj3 commented on src/schemas/user/updateUser.schema.ts
> +      .default(CompanyRole.CLIENT)
O mesmo se aplica para os valores default acima

2022-06-14 12:22 UTC, marcelosj3 requested changes

2022-06-14 12:22 UTC, marcelosj3 commented on src/schemas/user/serializedUser.schema.ts
> +export const serializedCreateUserSchema = object().shape({
Precisamos adicionar um endereço opcional nesse aba, ou criar um outro schema com endereço

2022-06-14 14:06 UTC, merged